services:
  Chromium:
    image: lscr.io/linuxserver/chromium:latest
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PUID: "1000"
      GUID: "1000"
      TZ: ${TZ}
    ports:
      - 3300:3000
      - 3301:3001
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    labels:
      runtipi.managed: true
      runtipi.appurn: chromium:_user
    hostname: chromium

