services:
  musicassistant:
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    network_mode: host
    environment:
      LOG_LEVEL: info
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /etc/localtime:/etc/localtime
    labels:
      runtipi.managed: true
      runtipi.appurn: musicassistant:_user

